hydra:
  run:
    dir: ./output/${parameters.batch_size}_${parameters.num_epochs}

parameters:
  data_dir: "/data/ntire20-datasetnoise/" 
  resume: "put-ckpt-name"
  ckpt_path: "ckpt"
  logs_path: "log"
  num_epochs: 100
  image_size: 64
  batch_size: 16
  num_workers: 12
  channel_img: 1
  vector_dim: 256
  features: 16
  lr_init: 2.e-4
  lr_step: 25
  lr_gamma: 0.5
  random_seed: 42
  verbose_step: 500
  optim_reset: False